### ISSUE TITLE
Unable to use log messages with spaces in docker

### ISSUE THREAD

**Issue by patros** [datalust/seqcli#109]
This command works...

```
docker run --rm datalust/seqcli:latest log --message="{ReleaseName}inproject{ProjectName}successfullfor{ReleaseEnvironment}" \
--property=ReleaseName="Test" \
--property=ReleaseEnvironment="Test" \
--property=projectName="***" \
--property=Environment=PRODUCTION \
--property=Service="***" \
--level=Information \
--server=https://***/ \
--apikey=***
```

This one does not...

```
docker run --rm datalust/seqcli:latest log --message="{ReleaseName} in project {ProjectName} successfull for{ReleaseEnvironment}" \
--property=ReleaseName="Test" \
--property=ReleaseEnvironment="Test" \
--property=projectName="***" \
--property=Environment=PRODUCTION \
--property=Service="***" \
--level=Information \
--server=https://***/ \
--apikey=***
```

With the message `Unrecognized options: in, project, {ProjectName}, successfull, for, {ReleaseEnvironment}`

I've also tried using -m instead of --message, using ` instead of ", and removing quotes from properties.

Running on Ubuntu 18.04 with docker ce latest package version `5:18.09.6~3-0~ubuntu-bionic`

**Comment by nblumhardt** [comment]
Thanks for the report :+1:

I notice you've tried backticks and double-quotes; any chance single quotes `'` work? It looks like a shell quoting problem, we'll be able to figure it out :-)

You might also try:

```shell
# etc...
CLIARGS='log --message="{ReleaseName} in project {ProjectName} successfull for{ReleaseEnvironment}"`
docker run --rm datalust/seqcli:latest "$CLIARGS"
```

Let me know if either of these helps. Cheers!

**Comment by patros** [comment]
My mistake @nblumhardt, I tried `'` not backticks.

**Comment by jmcstone** [comment]
I also have run into the same issue. I tried numerous combinations: 

docker run --net host datalust/seqcli:latest log -m "Hello, World"
Unrecognized options: World

docker run --net host datalust/seqcli:latest log -m 'Hello, World'
Unrecognized options: World

docker run --net host datalust/seqcli:latest log -m `Hello, World`
Hello,: command not found
The command failed: Missing required value for option '-m'.

I was able to get it to work by modifying the **run.sh** file to:

`#!/bin/bash
exec /bin/seqcli/seqcli "$@"`

Note the quotes around $@ (https://github.com/koalaman/shellcheck/wiki/SC2068)

The following commands then worked:
docker run --rm --net host seqcli log -m "Hello World"
docker run --rm --net host seqcli log -m "Hello {Name}" -p Name="Linus Torvalds"

Cheers

**Comment by nblumhardt** [comment]
Fantastic, thanks for passing that on @jmcstone , we'll give it a shot :+1:

**Comment by nblumhardt** [comment]
Just going to reopen so we can track the progress of #111

**Comment by nblumhardt** [comment]
The latest container image includes the fix, thanks all!
