### ISSUE TITLE
Ship the Windows distribution as a zip file

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seqcli#12]
**Edit:** we've decided to drop the standalone `seqcli` installer, and bundle the Windows distribution with Seq itself. See also: https://github.com/datalust/seq-tickets/issues/721.

**Comment by nblumhardt** [comment]
An alternative take on this, to avoid having to maintain a secret signing key, we could simply:

 * release the Windows binaries as a `.zip` file, the same way as we currently ship macOS and Linux binaries, and
 * merge the Windows zip file contents into the Seq installer proper, since most devs and admins who work with a remote Seq server will also have a local Seq install

On Windows this means the primary consumption mode would be to install Seq, which would automatically put `seqcli` on the `%PATH%`.

A side-benefit would be getting rid of yet another Windows installer to maintain :-)

Any thoughts? @KodrAus ?

**Comment by andymac4182** [comment]
Any chance of a `dotnet global tool` being an alternative source?

**Comment by nblumhardt** [comment]
This would be great 👍

**Comment by nblumhardt** [comment]
Done
