### ISSUE TITLE
Add command to delete/clear events

### ISSUE THREAD

**Issue by redoz** [datalust/seqcli#126]
It would be nice if it was possible to automate the deleting of all events from the command line.

**Comment by nblumhardt** [comment]
Thanks for the suggestion, we'll give this some thought.

**Comment by redoz** [comment]
Especially useful for those offline scenarios when you use seqcli to ingest log files:
1. acquire files (outside the scope of seqcli)
2. clean seq
3. ingest files

And thinking about it, it could even be a flag on "ingest":
```seqcli ingest --truncate --input=C:\temp\logs\* --server=http://localhost:7357/ --json```

**Comment by notes2c** [comment]
Are there any plans implementing this feature ? 

And it would also be nice if events could be delete based on a query.

**Comment by nblumhardt** [comment]
We'll revisit this again, thanks for the nudge :+1:

**Comment by nblumhardt** [comment]
We've reviewed this again and decided we'd rather not implement this. Manual event deletion is not intended to be a general feature in Seq, they're very much for emergency removal of accidentally-ingested data. Retention policies are almost always the better choice in production scenarios.

For local development scenarios, stopping Seq and removing the `Stream/` folder under Seq's storage root is a suitable alternative for truncation.

Thanks again for all the input and feedback, though.
