### ISSUE TITLE
[Enhancement] Command for workspace

### ISSUE THREAD

**Issue by andreas-nesheim** [datalust/seqcli#130]
With the introduction of workspaces, it would be nice to have a command to work with them from the CLI, f.ex. creating and deleting workspaces. Possibly for adding signals to a workspace aswell. This would help a lot when provisioning new servers with Seq logging or when you want to set up logging in multiple environments/servers.

Suggested commands:

Create a new workspace:

`seqcli workspace create -t 'My Workspace'`

Remove a workspace:

`seqcli workspace remove -t 'My Workspace'`

List available workspaces:

`seqcli workspace list`

Add a signal to a workspace:

`seqcli workspace addsignal --workspace 'My Workspace' --signal-id signal-205`

Remove a signal from a workspace:

`seqcli workspace removesignal --workspace 'My Workspace' --signal-id 205`

**Comment by nblumhardt** [comment]
Thanks for the suggestion! We'll give this one some thought :+1:

**Comment by nblumhardt** [comment]
Merged! 🎉 :-)
