### ISSUE TITLE
Populate a Seq instance with sample data

### ISSUE THREAD

**Issue by tsimbalar** [datalust/seqcli#133]
It would be great for demonstrations, exploring the Seq features etc to be able to populate an instance of Seq with sample data. 

I would imagine it should be possible to do it from some admin menu, or through the CLI. 

Ideally it would insert in Seq : 
- tons of events with a variety of `SourceContext`, `MachineName`, `AppName` etc ... but enough in common to show correlation and similar stuff
- with a property that allows to distinguish them from real data (an arbitrary property), and possibly allows to delete it easily

RavenDb has [a similar feature](https://ravendb.net/docs/article-page/4.1/csharp/studio/database/tasks/create-sample-data), and it is super helpful to do demos or simply learn about the tool.

**Comment by andymac4182** [comment]
@tsimbalar Would a URL to load the example data work for you? I was having a think about this and as Seq can handle different languages and logging pipelines.  I can see it being good to be able to load the sample data from a website the can be expanded to show different examples for libraries like `pino` vs `serilog` vs `docker gelf` logs.

This would allow the data to be relative to now and just use the normal ingestion pipeline. Using curl or similar to download the data and then send that data to `seqcli ingest`.

**Comment by tsimbalar** [comment]
I think I cared mostly about having "realistic" enough data, but mostly quality data that allows to show correlation filtering and all the features of Seq.

Having it still streaming data "realtime" would be even better but maybe not necessary.

**Comment by andymac4182** [comment]
Ahh. Live data would be good.

**Comment by nblumhardt** [comment]
`seqcli sample setup` (create signals and dashboards) and `seqcli sample ingest` (stream in high-quality sample events) is now on `dev`! 😎 

Great to finally move this forward, it's been on the radar so long - if you have a chance to check it out, we'd love to hear your thoughts.
