### ISSUE TITLE
Consider also distributing your cli-tools as "dotnet tool"s

### ISSUE THREAD

**Issue by penenkel** [datalust/seqcli#143]
Obviously there many ways to distribute tools and which one is "the best" is a highly subjective and situational topic, nevertheless I would appreciate being able to install all or any of the seq related cli-tools as a "dotnet tool".

Pros:
- can be installed globally or just project scoped
- distributed via NuGet and as such established procedures exist for both online and offline usage
- can easily be installed in automated environments/CI
- cross-plattform

Cons:
- requires dotnet-sdk to be installed
- additional effort

I realize that from a purely maintenance view-point this can be seen as additional effort with limited applicability. But I hope that the required effort isn't quite so large as one might think. I recently tried it with your clef-tool and following this [tutorial](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create) I was able to get it to work locally with 3 lines of code in less then 15 minutes. Obviously some more work would be required integrating it in the existing CI-workflows and filling out the nuget properties, but that should be nothing new.

**Comment by nblumhardt** [comment]
Thanks for the suggestion 👍

**Comment by nblumhardt** [comment]
Closed in #152
