### ISSUE TITLE
Signals are duplicated on import

### ISSUE THREAD

**Issue by AlbertoSadoc** [datalust/seqcli#145]
When using `signal import` the signals that have an id of an already existing one are added as duplicated with a new id instead of updating the existing one.

It can be easily reproduced by running `seqcli signal list --json`, saving the result in a file called test.json and then importing with `seqcli signal import -i ./test.json`.

I tried with both shared and owned ones and the result is the same.

Seqcli version 2020.1.304

**Comment by nblumhardt** [comment]
Closed in #147
