### ISSUE TITLE
Signal create should allow definition of included columns

### ISSUE THREAD

**Issue by crazycrank** [datalust/seqcli#146]
The `signal create` command currently only supports the creation of filter signals. There should be a `-c` option, which accepts an array of columns (or allows for multiple `-c` arguments at once), which are then included in the signal definition.

**Comment by nblumhardt** [comment]
Thanks for the suggestion :+1:

**Comment by crazycrank** [comment]
Awesome thanks a lot. Sadly not using it in my current project, but I'm looking forward to try it in the future!
