### ISSUE TITLE
Count is not always respected in partial search return

### ISSUE THREAD

**Issue by nskerl** [datalust/seqcli#169]
When using the `search` command the `--count` parameter is ignored if the resultset is large enough to be _partial_.

I'll take a guess that this line [here](https://github.com/datalust/seqcli/blob/5dc5991b0943d831190cbfec80c00c6d26b46579/src/SeqCli/Cli/Commands/SearchCommand.cs#L91) is related.

Here is a quick example using a simple search:
```
$start = (get-date).AddDays(-1)

(seqcli search -f "has(ApplicationId)"  --start=$start --signal="signal-2596" --count 1).Count
1

(seqcli search -f "has(ApplicationId)"  --start=$start --signal="signal-2596" --count 10).Count
10

(seqcli search -f "has(ApplicationId)"  --start=$start --signal="signal-2596" --count 100).Count
100

(seqcli search -f "has(ApplicationId)"  --start=$start --signal="signal-2596" --count 250).Count
4029
```

**Comment by nblumhardt** [comment]
👍 thanks for the report. That is indeed a suspicious looking line...
