### ISSUE TITLE
Locale support for syslogdt

### ISSUE THREAD

**Issue by pfeigl** [datalust/seqcli#180]
`syslogdt` (and I think other formats) are currently only parsed in `InvariantCulture`.

We are (unfortunately) running on a german system. This outputs dates like the following in syslog `Mär 10 16:50:19`.

It would be great if there'd be an option to control the culture atleast to some extent.

**Comment by nblumhardt** [comment]
Just dropping a quick update here, we'd be supportive of someone taking the time to scope this out and propose a solution, but don't currently expect to take any action on it. I'll close this now to reflect that, but if anyone following along is interested in giving this a shot, please feel free to chime in.
