### ISSUE TITLE
`seqcli ingest --json` cannot accept CLEF events with numeric values for `@i`

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seqcli#186]
The CLEF format, and Seq, both support numeric event types, but `seqcli ingest --json` fails with

> System.IO.InvalidDataException: The value of `@i` on line 1 is not in a supported format.

The exception is raised here: https://github.com/serilog/serilog-formatting-compact-reader/blob/dev/src/Serilog.Formatting.Compact.Reader/LogEventReader.cs#L181

And the related TODO is here: https://github.com/serilog/serilog-formatting-compact-reader/blob/dev/src/Serilog.Formatting.Compact.Reader/LogEventReader.cs#L162

**Comment by KodrAus** [comment]
We also can't currently accept the `@i` property through seqcli because it's not specially handled in `SurrogateLevelAwareCompactJsonFormatter.FormatEvent`. It'll get escaped as `@@i`.
