### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by mcflux** [datalust/seqcli#195]
Hi
just discovered that there is a choco package for seq, but not for the seqcli.
We create ansible script sthat install seq and we would like to automate setting signals and configuration with command line as well. So installing that with choco would be great

Thank you

**Comment by nblumhardt** [comment]
@mcflux the Seq package does also include/bundle `seqcli`, and puts it on the path, so you may not need an extra package, depending on how your deployments are set up.

It's not likely at this stage that we'll ship `seqcli` separately on Chocolatey; though, it is distributed as a .NET global tool, so `dotnet tool install --global seqcli` if you have `dotnet` in your environment already.

Let me know if this helps 👍

**Comment by nblumhardt** [comment]
Closing as stale, but thanks again for the input!
