### ISSUE TITLE
Seqcli sample data error: "403 - Only shared or personal signals can be created."

### ISSUE THREAD

**Issue by juchom** [datalust/seqcli#200]
I'm running Seq locally in a docker container on windows with port 5341 & 8080 exposed on localhost

I have created the api key with all the permissions :

![image](https://user-images.githubusercontent.com/17902415/120345100-770ec000-c2fa-11eb-95fb-20d023f86218.png)

And when I try to run sqlcli with this command :

```console
docker run --rm -it --network host datalust/seqcli sample setup -s http://127.0.0.1:5341 -a qKQP.....
```

 I have this error message :

> The command failed: 403 - Only shared or personal signals can be created.

**Comment by nblumhardt** [comment]
Hi Julien, thanks for the report.

I think I know what's going on, here (a bit of a rough edge we need to smooth out!)

Is your API key a "system" one? And if so, does the command work when you use an API key created in your personal user preferences, instead?

Best regards,
Nick

**Comment by juchom** [comment]
I think it's a system api key. I pulled the docker image and add the key. I made nothing more.

**Comment by nblumhardt** [comment]
Thanks for the follow-up. I think we'll need to do additional work to support setting up with system API keys. A personal key should succeed now, though.

**Comment by clabnet** [comment]
I have the same identical issue

**Comment by nblumhardt** [comment]
Hi @clabnet - if it's the same issue as above, it will be because you're using a system API key, rather than a personal one, to configure `seqcli`. Does the command succeed with an API key created through your Seq user preferences screen?

**Comment by clabnet** [comment]
Hi Nick, 
yes, the command has now succeeded with API key created by User -> Preferences -> API Key. 
Thank you.

**Comment by nblumhardt** [comment]
Fixed in https://github.com/datalust/seqcli/pull/242
