### ISSUE TITLE
Powershell tail

### ISSUE THREAD

**Issue by pitermarx** [datalust/seqcli#208]
I'm not sure why but `Get-Content .\myLogFile.log -Tail 1 -Wait | seqcli ingest -json` does not work.
Nothing gets to logged to seq, not sure even how to debug it

But this works
`Get-Content .\neptune20211008.log -Tail 1 -Wait | % { $_ | seqcli ingest -json }`

I suspect the latter is not optimized cause it will ingest one line at a time

**Comment by nblumhardt** [comment]
Howdy! Is it possible the argument `1` to `-Tail` is throwing things off? I.e. if you just `-Tail` without the count, does it work as expected?

You're right about the performance of the second option above - invoking `seqcli` for each line will be slow 👍

**Comment by pitermarx** [comment]
The Tail argument needs a count. It means get the last X lines.
Well, you can close this... It started working today. No idea what's diferent....

**Comment by pitermarx** [comment]
Well I figured out why the first one does not work.
Powershell pipelines are they're own kind of thing
https://www.sapien.com/blog/2019/05/13/advanced-powershell-functions-begin-to-process-to-end/

But I still have the problem how to pipe efficiently.
My best guess would be a manual loop+sleep and calling ingest in each iteration

**Comment by nblumhardt** [comment]
Closing this one as stale, but thanks for all the discussion 👍
