### ISSUE TITLE
Publish an ARM docker container for seqcli

### ISSUE THREAD

**Issue by KodrAus** [datalust/seqcli#227]
This is needed for https://github.com/datalust/sqelf/issues/94

We already have ARM binaries available, but currently just build and publish an x86-based Docker container. We should be able to use the same manifest approach we do with the Seq container to stitch up a single image from multiple architectures.

**Comment by charleskorn** [comment]
I'm not sure if this is now complete with #228 having been merged, but if it is, something is not quite right: Docker Hub is showing that the image for `seqcli` has two variants, both for `linux/amd64`, and the `-arm64` tags (eg. [`2022.1.567-arm64`](https://hub.docker.com/layers/seqcli/datalust/seqcli/2022.1.567-arm64/images/sha256-da05bb056a68afac37c429caa4ac32559e2571fee21435a52facab95eedf012d?context=explore)) are showing up as for `linux/amd64` as well.

**Comment by KodrAus** [comment]
Thanks for the heads up @charleskorn. Something doesn't look right there does it. I'll take a look :eyes:

**Comment by ankithkonda** [comment]
Hey @KodrAus, I'm trying to use this on m1 mac, but I'm getting this - 
```
> docker run datalust/seqcli
Unable to find image 'datalust/seqcli:latest' locally
latest: Pulling from datalust/seqcli
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
See 'docker run --help'.
```

I see a few PRs merged as part of this, and I see the arm64 dockerfile, is this a known issue?

**Comment by KodrAus** [comment]
Hi @ankithkonda :wave: Hmm, it looks like our `seqcli` images are targeting `arm/v8` rather than `arm64/v8`. I'll dig into it and see what's going on there.

**Comment by ankithkonda** [comment]
Thanks for the quick response @KodrAus, much appreciated 🙂

**Comment by KodrAus** [comment]
It looks like things are fixed for images coming out of CI now. I've opened #247 to get a stable release together. I'll loop back here once that's published.

**Comment by KodrAus** [comment]
Looks like I missed looping back here, but we have stable ARM images published and working again :tada:
