### ISSUE TITLE
Confused, what's the purpose of seqcli?

### ISSUE THREAD

**Issue by pcgeek86** [datalust/seqcli#234]
I just randomly came across `seqcli` by noticing it in the scoop package manager's metadata, during an update (see below).
I figured I would research it to see what its purpose is.
It looks "cool," but I'm a little confused on where `seqcli` is intended to be used.

- If you're a developer, wouldn't you just use a logging library that's native to your language? 
- What's the advantage of using `seqcli` instead of your native logging library?
- Does `seqcli` offer a "local" and "server" mode? This isn't obvious from the README.
- Is `seqcli` intended to be used as part of a commercial product? I noticed it has a `license apply` command, even though it's open source. 

```
C:\Users\TrevorSullivan> scoop install tektoncd-cli
Updating Scoop...
Updating 'extras' bucket...
 * 812ef92e1 ubports-installer: Update to version 0.9.3-beta             4 hours ago
 * 4d9f5a56d microsoft-powerapps-cli: Update to version 1.13.4           4 hours ago
 * 6ff47d362 ipfs-desktop: Update to version 0.20.3                      4 hours ago
Updating 'main' bucket...
 * 00e28352b minio: Update to version 2022-03-22T02-05-10Z               13 minutes ago
 * c34c22772 clink: Update to version 1.3.12                             13 minutes ago
 * 392b89af4 volta: Update to version 1.0.6                              4 hours ago
 * 4f4cda2e1 seqcli: Update to version 2022.1.567                        4 hours ago
 * 28a91c16b meson: Update to version 0.62.0                             4 hours ago
 * 3de1ac9f9 jx: Update to version 3.2.265                               4 hours ago
 * 10f6c677a git-xargs: Update to version 0.0.14                         4 hours ago
 * f01318aa8 gdu: Update to version 5.13.2                               4 hours ago
 * 3ae2c520c fossa: Update to version 3.1.5                              4 hours ago
 * 3f8c165ae firebase: Update to version 10.4.1                          4 hours ago
 * 13a456207 aws-sam-cli: Update to version 1.41.0                       4 hours ago
Updating 'nerd-fonts' bucket...
Updating 'nonportable' bucket...
Scoop was updated successfully!
```

**Comment by nblumhardt** [comment]
Hi @pcgeek86 👋

Not sure how familiar you are with Seq (https://datalust.co/seq), but if you haven't checked it out, that would be the missing link and probably explain `seqcli`'s purpose :-)

`seqcli` is a command-line client for Seq's HTTP API, so the purpose of `seqcli` is automating all of the things you'd normally do with Seq.

HTH!

**Comment by pcgeek86** [comment]
Nice, thanks! I hadn't seen that. Looks like an alternative to ElasticSearch?
