### ISSUE TITLE
/bin/seqcli/seqcli: not found

### ISSUE THREAD

**Issue by mrfelton** [datalust/seqcli#267]
Getting the following error when trying to use the latest `datalust/seqcli:2022.1` docker image.

```
/bin/seqcli/seqcli: not found
```

`datalust/seqcli:2022.1` works fine but I can't use this because I'm running on an Apple M1 and the older image is not built for that architecture.

When I sh into the container I can see that `/bin/seqcli/seqcli` does exist, which is strange.

**Comment by nblumhardt** [comment]
Thanks for the heads-up. I'm not on an M1 so can't dig in immediately, though as soon as we're back in the office we'll be able to take a proper look.

Are both `datalust/seqcli:2022.1.621-arm64` and `datalust/seqcli:2022.1.621-arm64` broken for you?

As a workaround in the meantime, you can grab ARM binaries directly from https://github.com/datalust/seqcli/releases - let me know if you run into any difficulties.

**Comment by KodrAus** [comment]
Thanks for the report @mrfelton! This should be fixed by #268, which is currently available in the `datalust/seqcli-ci:2023.1.665-arm64` image. We're currently working on getting a stable release put together which should include this.
