### ISSUE TITLE
Filters on levels match original text rather than transformed value

### ISSUE THREAD

**Issue by KodrAus** [datalust/seqcli#280]
Given a text log like:

```
25544 11:28:40 WARN  The "SessionExpirationThreadCount" setting contains an invalid value. The default value is used instead. Invalid value: "". Default value: "8"
```

and an ingest call like:

```
seqcli ingest -i log.txt -x "{Thread:nat} {@t} {@l:level} {@m:*}{:n}{@x:*}" --filter="@Level='Warning'"
```

no data will be ingested. If we change the filter to:

```
seqcli ingest -i log.txt -x "{Thread:nat} {@t} {@l:level} {@m:*}{:n}{@x:*}" --filter="@Level='WARN'"
```

then it will.

This is a problem because in Seq the `@Level` property will have the value `Warning`, not `WARN`, so the filter we write there is different than the one we ingest with.

**Comment by nblumhardt** [comment]
In Seq the value should be `WARN` too, Seq no longer normalizes levels to any specific set of values. It may be a problem in how seqcli is holding Serilog.Expressions 🤔

**Comment by KodrAus** [comment]
I think we do normalize the level when using the `:level` matcher, but that doesn’t appear to take effect until after the filter is run.

**Comment by nblumhardt** [comment]
@KodrAus ah I see you were already ahead of me on the `:level` matcher 😅 

With #281, the filter will see `WARN` if `{@l}` is extracted, and `Warning` if `{@l:level}` is used.
