### ISSUE TITLE
Not clear what API key permissions are required for each command

### ISSUE THREAD

**Issue by iainsproat** [datalust/seqcli#290]
It is not clear from the documentation or the `help` command alone as to which API key permissions are required for each command I may wish to run using the CLI.

I would like to maintain the principle of minimum permissions as a security best practice, so an API token should only be granted exactly what is required to achieve a task. Presently I'm getting some 403 errors as I've assigned too restrictive a permission.

**Given** I know which CLI commands I wish to run,
**When** I read the documentation
**Then** I should know what minimum permissions I should assign to my API key to enable the CLI command the API key is used with to run without a `403` error.

**Comment by liammclennan** [comment]
Hi @iainsproat,

The CLI is a client for the HTTP API. Looking at the [api documentation](https://docs.datalust.co/docs/server-http-api) you can see the required permissions.

I'll look at adding a note to the seqcli documentation.

**Comment by liammclennan** [comment]
Updated docs: https://docs.datalust.co/docs/command-line-client#permissions
