### ISSUE TITLE
`ingest` JSON:  How to specify the property to use for `@m`?

### ISSUE THREAD

**Issue by richard-stafflink** [datalust/seqcli#370]
When using `ingest` how do I set the "message" property to use?

I'm using Pino (JS logger) to output to a file (rows of JSON), and the "message" property is not what Seq expects (`@m` or `@mt`). We ship directly to Seq normally, but in CI a log file is used only. So when there is an error/issue we can download the log file and import to a local dev instance of Seq for searching/viewing.

Is there a way when using `ingest` of specifying the `@m` field/property to use, or should I augment log entries with `@m = msg`

**Comment by richard-stafflink** [comment]
![image](https://github.com/user-attachments/assets/7df96447-4744-4e27-be1b-beb782f16c96)

Looks like `time` is not being mapped to `@t` either.
But `level` works as expected.

**Comment by nblumhardt** [comment]
Hi @richard-stafflink!

The accepted format for JSON events is documented in:

https://docs.datalust.co/docs/posting-raw-events#reified-properties

You'll need to use something like `jq` (or your shell) to rename properties on their way in, there's not currently any mapping support in `seqcli ingest --json` (though it'd be really nice to add 🤔 ...).

**Comment by richard-stafflink** [comment]
Created a script to do fix up the logs:

```bash
#!/bin/bash

cp ./api.log.json ./api.log.jsonc

# replace "msg": with "@m":
sed -i 's/"msg":/"@m":/g' ./api.log.jsonc
# replace "timeServer": with "@t":
sed -i 's/"timeServer":/"@t":/g' ./api.log.jsonc

# Levels
sed -i 's/"level":20/"@l":"Debug"/g' ./api.log.jsonc
sed -i 's/"level":30/"@l":"Info"/g' ./api.log.jsonc
sed -i 's/"level":40/"@l":"Warning"/g' ./api.log.jsonc
sed -i 's/"level":50/"@l":"Error"/g' ./api.log.jsonc
sed -i 's/"level":60/"@l":"Fatal"/g' ./api.log.jsonc

# Copy the file to the container
docker cp ./api.log.jsonc local-seq:/api.log.jsonc

seq-cli () {
  docker exec -it local-seq /seqsvr/Client/seqcli $@
}
# alias seq-cli="docker exec -it sauron-seq /seqsvr/Client/seqcli"
seq-cli ingest -i /api.log.jsonc --json -p LOG_SOURCE=file
```
